### ISSUE TITLE
Consider a "This Side Up" label

### ISSUE THREAD

**Issue by DusteDdk** [monotech/MOS_CPU_Replacer#2]
Entirely my own fault, but after being presented with blank screen I discovered that my intuition about the orientation was wrong (I should have consulted pictures before I started, but I was lulled into a false sense of security by all the instructions and it slipped my mind) :)

Still, it might be nice if it's possible to find a little spot for "This side up" in the next revision.

Also, thanks for doing all this awesome stuff! :+1:

**Comment by monotech** [comment]
Oh dear! "This side up" label sounds good. I'll add it to the next version
which I'm working on (with fixed 8501 support at least).

It may work if you desolder and install things where they should go.
Depends where things really ended up being wired.

**Comment by DusteDdk** [comment]
Yeah, I guess it should, it was exactly "upside down" (that is, the surface mount ICs were on the bottom instead of the top) but the notch was in the right orientation :) unfortunately, I entirely scewed up the desoldering process, so I'll just order another kit when/if they become available again xD Thanks for adding the label, it will help someone in the future I'm sure. No idea how I didn't stop and think "Hey, which side of the PCB should I put the socket on" :D
