### ISSUE TITLE
Can't get mine working?

### ISSUE THREAD

**Issue by ghost** [monotech/MOS_CPU_Replacer#3]
I had a round of these made by JLCPCB, with the goal of using them as a 6510 replacement for some new DIY C64 builds, but so far I haven't been able to get them working?

I've tried several known working 6502's - some from AliEx, but others from working 1541 disk drives, but all are failing with similar errors... 

The C64 shows a black-screen, and a Deadtest cart won't even work. 

I also tried running some tests using a Backbit tester on the MOS 6510 setting, but this is showing failures on:
> A=aec
> I=peripheral IN
> O=peripheral OUT
> N=interrupt
> W=walking

The only DIY bits that JLCPCB didn't do for me were the jumpers, the pin headers and the machine pin socket, which I hope I've done correctly (see images)...

Appreciate any assistance...

![IMG_0916](https://user-images.githubusercontent.com/61174362/169665873-6b9158f6-57cd-4b1f-85b3-abb1a1b90f1a.jpeg)

![IMG_0912](https://user-images.githubusercontent.com/61174362/169665882-922e5009-8b1b-490d-89cb-864d38a85c31.jpeg)

![IMG_0914](https://user-images.githubusercontent.com/61174362/169665887-dcdd1cda-8d1b-4fcb-96aa-01c6dffc4ffc.jpeg)

![IMG_0915](https://user-images.githubusercontent.com/61174362/169665895-ea5d1c65-0c0b-488b-b024-e61a39bb8067.jpeg)

![IMG_0907](https://user-images.githubusercontent.com/61174362/169665897-f4eb6db3-c301-49ec-8144-4c0041deca68.jpeg)

![IMG_0913](https://user-images.githubusercontent.com/61174362/169665900-731348c2-5c20-4942-96d0-607e2c145948.jpeg)

![IMG_0903](https://user-images.githubusercontent.com/61174362/169665901-40d402bc-b608-4f2f-81ea-bacfa6f2ad4b.jpeg)

![IMG_0906](https://user-images.githubusercontent.com/61174362/169665902-09c57d2b-acc1-4d30-a57b-ab69671d4d93.jpeg)

![IMG_0911](https://user-images.githubusercontent.com/61174362/169665904-2d8f19a1-850a-4f9c-8078-94040fe43209.jpeg)

**Comment by monotech** [comment]
Hello

Your MOS 6502A definitely have fake markings, but most fake marked chips
still work, although some are marked with a different model.
Even if yours are actually 65C02, they will work to boot the C64, but many
games and demos would crash.

Where did you get your HCT273s from? Their markings also look dubious.

Cheers
JD

**Comment by ghost** [comment]
Thanks @monotech - Appreciate the reply.
I've tried a few different 6502's, including a couple that I pulled from working 1541 drives, all have the same issue.
Due to supply chain issues, JLCPCB didn't have the HCT273's, so I wound up sourcing these from an eBay seller.
I'll have to try out some chips another source to see if they're the issue...

**Comment by monotech** [comment]
I suggest getting a TSSOP to DIP adapter and trying your HCT273s in a logic
tester (such as a TL866 programmer).

**Comment by ghost** [comment]
@monotech - Good idea. The adapter shows that the 273's are working... 

![IMG_0018](https://user-images.githubusercontent.com/61174362/170805849-c290c46c-4c68-49a2-b1d3-f392c4f21dc3.jpeg)

![IMG_0020](https://user-images.githubusercontent.com/61174362/170805850-e3e27de6-44db-47a7-bfad-68701242c57d.jpeg)

**Comment by monotech** [comment]
Hmm.. I'm not too sure sorry :/
I can only think of ensuring the HCT273s are soldered correctly since you hand-soldered them, and they're fine pitched.

**Comment by ewsz** [comment]
> 

The 6502 in your 1541 is most certainly a MOS 6502 which can comply with 1MHz. You need a CPU at least good for 2MHz - like a MOS 6502A or an R6502A. The CPU on the photo should be fine, of the markings are real.

**Comment by ghost** [comment]
Well, this update is coming nearly ~1 yr later because I had put this project on hold to work on other things.

In short, I simply hadn't shorted the"**W**" pad on the bottom of the board.

Once that was done, my modules are working perfectly now... 

I should also point out that there are MANY, MANY fake MOS 6502's being sold on AliEx. In my experience, these tend to be Atari "Sally" compatible and will not work in a C64! So, buyer beware!

**Comment by monotech** [comment]
The PCB has W shorted by default with a track. Perhaps you cut it at some point in order to use a W65C02S ?

**Comment by ghost** [comment]
The documentation does indeed show that "W" should be shorted by default, but I must have manufactured an older PCB rev, because _none_ of boards I had made last year had this pad closed be default?

I picked the project up again a couple of weeks back because I had an itch to get this going again, which is when I noticed the oversight on my part. Once I added the short, all of my boards worked...

This is a great project and a valuable asset that will help to keep the C64 alive, so thank you for that!
